### ISSUE TITLE
提议

### ISSUE THREAD

**Issue by xiaoguan-dot** [seewo-geek/seewoGeekWiki#21]
![于2024-06-22T18:59:00+08:00的聊天](https://github.com/seewo-geek/seewoGeekWiki/assets/100571246/ce7c1811-4ba1-49de-991f-d0685a272221)
![](https://github.com/seewo-geek/seewoGeekWiki/assets/100571246/ba7d5df1-1708-4f0e-8ee1-3787dc7e0237)

综上所述 我的提议是 在群内加一个机器人 该项目有新的合并请求后 通过机器人(基于WebHook)**发布新群规/修正案到群内**

且群规内也没有注明**违反该项群规的后果**，以及**群机器人**的**检测阈值**

所以建议在`请不要在群里使用诸如“6”、“。。。”之类的引人烦躁的没有意义的用词`添加：`，在您发送这些词大于等于五次后，您将会被移出聊群并移入黑名单`（血肉教训）

人话：也没人和我说发`6`和`...`会被移出去啊，嗖的一下，**我都没反应过来**...（↙这个地方又双叒叕违反群规了）

最后，感谢你的阅读.如果您是管理员，也望采纳鄙人的意见

（To 管理：所以，移入黑名单后多久能出来啊）
（To 想进群的群友：不！要！发！6！会！被！[【希沃售后业绩冲击部管理组】尊敬的...][系统消息：您已被移出聊群]）

------
**English version using machine translation**
To sum up, my proposal is to add a bot to the group, and after the project has a new merge request, publish the new group rules/amendments to the group through the bot (based on WebHook) **

And the group rules do not indicate the consequences of violating the group rules, as well as the detection threshold of the group robots.

Therefore, it is recommended to add: "Please do not use annoying and meaningless words such as" 6 ","... "in the group. After you send these words more than five times, you will be removed from the chat group and blacklisted." (flesh and blood lesson)

Human words: No one told me that 6 and... will be moved out, whoosh, ** I didn't even react **... (↙ this place is violating the group rules again)

Finally, thank you for reading. If you are an administrator, please take my advice.

(To manage: So, how long can you come out after being moved to the blacklist?)
(To the group friends who want to enter the group: No! Want! Send! 6! Will! Be! [[Xiwo After-sales Performance Impact Department Management Team] Dear...] [System message: You have been removed from the chat group])

**Comment by xiaowuap** [comment]
I may not be able to understand the content of what you said.
Closing issue....
